src/deprecation.h, src/main.cpp, src/rpc/mining.cpp, src/rpc/zelnode.cpp, src/zelnode/spork.cpp, src/zelnode/zelnodesync.cpp, src/zelnode/zelnodesync.h
- Add checks to getblocktemplate - This should stop pools from sending miners data packets if they aren't synced with the zelnode data
- Remove spamming on logs
=> Zelnode update in lastest version

src/chainparams.cpp
Update logic so that we don't go below the height of zero when checking the upgrade state
=> Fix assert zero check

src/zelnode/zelnodesync.cpp, src/zelnode/zelnodesync.h
- Some pools were having trouble getting out of sync with the zelnode data. This put them in a state were they weren't mining blocks as **getblocktemplate** was returning an error
These changes should allow for those nodes to get back in sync without having to interact with the node. The node should handle this automatically. 
If the node isn't able to get it back on track. The rpc command `znsync reset` can be used to force a resync of the zelnode data.
=> Update zelnode sync parameters

src/rpc/zelnode.cpp
Adds filtering through pubkey in listzelnodes command.
Backgorund:
ZelFlux receives messages from other nodes that are signed by the this zelnode keypair. Adding ability to filter listzelnodes via public key (that is part of the message) reduces computation in zelflux that does not have to do find operation to get the correct zelnode object.
=> listzelnodes - filter in pubkey

src/wallet/rpcwallet.cpp
This PR adds confirmations and time field to z_listreceivedbyaddress rpc call.
Background: This is essentially useful for wallets such as zelcore that now need to run another gettransaction call to get those fields. And so this PR reduces the number of calls a wallet needs to make to a daemon.
=> Rpc features

depends/packages/libsodium.mk
This PR fixes the macOS build that is currently failing due to the download path for Libsodium changing - mentioned in Zcash issue [4295](https://github.com/zcash/zcash/issues/4295)
=> Update libsodium download-path

src/net.cpp
-> do not bind port on to child process - zelbench
https://stackoverflow.com/questions/38191726/c-how-to-prevent-child-process-binding-port-after-fork-on-linux
Closes #110 
coauth @XK4MiLX
=> fix port binding

src/rpc/rawtransaction.cpp
Zelcash daemon on zelnodes are crashing on v4.0.4
We are suspecting the lines commented are the cause combined with the multiple calls from zelflux.
Lines were commented until furter investigation.
=> Fix Possible cause of daemon crash of V4.0.4

src/main.cpp
Changed PartitionCheck method that is scheduled to be executed every 120 blocks.
When a warning error was found on this method it was never cleared.
Not at begining of execution the warning error message is cleared, if it's ok it will desapear from "errors" on RCP calls.
=> Clear Partition Check Warning Message

src/main.cpp, src/pow.cpp, src/undo.h, src/zelnode/zelnode.cpp
Nodes were stuck on the network:
- Added it into the undoblock database, and made sure that if a block is undone, that the old ipAddress is restored
What I think happened: 
- A flux node was confirmed on the network with Ip Address: **A**
- 5 blocks later it sent a new confirmation tx to the network in which an ip address change was made to Ip Address: **B**
- The tx was mined into a block, and broadcasted out as block: **1**
- Another block was also mined that orphaned block **1**, and replaced it: calling it block **2** 
- Because this lastIpAddress logic wasn't in place, when block **1** was orphaned its ip address stayed as **B**, instead of reverting back to **A**.
=> Add missing lastIpAddress logic into undoblock

src/chainparams.cpp, src/main.cpp, src/rpc/blockchain.cpp, src/rpc/zelnode.cpp
45202f784cb6f733de0e31614f232040ffc725fb -> This logic was inherited from zcash, and I do not think it is needed anylonger. It is causing crashes on machines that are syncing from scratch because it tries to check an OutOfBounds height in the chainActive array. 
5235d832a483f5b35a54117ae4b9bf02a4bbe304 -> Nodes were crashing during sync, this was one of the backtraces. Hoping that this commit fixes the problem that were occuring. 
`(gdb) backtrace
#0  __memcmp_sse4_1 () at ../sysdeps/x86_64/multiarch/memcmp-sse4.S:1529
#1  0x0000555555810cd3 in operator< (b=..., a=...) at ./uint256.h:93
#2  operator< (b=..., a=...) at ./primitives/transaction.h:342
#3  std::less<COutPoint>::operator() (__y=..., __x=..., this=0x5555564bd150 <g_zelnodeCache+592>) at …
=> Remove unneeded logic from IsInitialBlockDownload causing crashes

src/rpc/zelnode.cpp, src/zelnode/benchmarks.cpp
strPath is being set only if node is a flux node. Doing flux related rpc commands relying on that variable causes node to crash.
=> prohibit flux node rpc if not a fluxnode

src/rpc/zelnode.cpp, src/zelnode/zelnode.cpp, src/zelnode/zelnode.h
- The **mapZelnodeList** contains confirmed and expired flux nodes, and shouldn't be used for accurate counts.
- Instead, we should only use the **mapConfirmedZelnodes** for accurate counts. 
- Updated **getzelnodecount** to also return accurate counts based on the zelnode Tier.
=> Fix getzelnodecount to be more accurate

src/miner.cpp
The following error occurred on a pool. This commit should fix the issue from happening ever again. 
`
zelcash-cli  getblocktemplate
CreateNewBlock(): TestBlockValidity failed: zelnode-tx-invalid-confirm-outpoint-not-started
`
=> Remove tx from mempool if it is going to throw error

src/main.cpp, src/zelnode/zelnode.cpp, src/zelnode/zelnode.h
- Peers are sending transaction they think are valid, if this is a confirmation transaction that just got mined, we fail to accept it and DOS them. Instead, we do a check before we confirm the transaction it valid to see if it meets confirmation window. If not, we drop the transaction network message and move on
- Added ability for Zelnode transactions to override other transaction in the mempool if they have a newer sigTime in the transaction. Should help stuck transactions in the mempools that aren't being mined
- Cleaned up some code in zelnode.cpp, and move it to a function so it can be used in AcceptToMemoryPool, and ContextualCheckTransaction
=> Fix mempool, clean code, stop dosing peers

src/main.cpp
- Someone ran into an issue where they couldn't start a zelnode. This check was failing for some reason. I am assuming it is because of how OSX assigns default values to int8_t (this is a guess)
- Fixed the problem by only checking on `tx.nType == ZELNODE_CONFIRM_TX_TYPE && tx.nUpdateType == ZelnodeUpdateType::UPDATE_CONFIRM `  . We don't want to do this check on starting zelnode transactions.
=> Make zelnode type check more strict

src/zelnode/zelnode.cpp
Cumulus and Nimbus count were swapped on rcp getzelnodecount
=> Fix getZelNodeCount cumulus and nimbus count swapped

src/main.cpp
- Missed this addition, this should fix the problem with pools finding invalid blocks. 
- Moved zelnode replace transaction log to **Zelnode** category - Progress on less log spam by default
=> Always use the height during the check

src/chainparams.cpp, src/checkpoints.cpp, src/checkpoints.h, src/main.cpp, src/txmempool.cpp, src/txmempool.h
a1538a1d3779ab8c0e9612cb1ece7d818e818930 - Makes is so we don't keep checking zelnodes txes that we already received in a previous block, failing the check and throw an error to the logs.... so less errors in logs that don't help. 
1c8c8be9812f05be057a9cecfb8b4054f55d6d7e - Makes is so we actually use the checkpoints data in chainparams for validating blocks at certain heights. This change fixes reindex on nodes with messy block databases. 
7ae3580a98aca4299131b129ad859b17d48628a1 - Missed addition in destructor 
I have ran this for the following tests: 
1. Fresh sync - Successful
2. Reindex on messy block node db - Successful, Failed without 1c8c8be9812f05be057a9cecfb8b4054f55d6d7e
3. Reindex on fresh synced node - Successful - Was successful without …
=> Verify checkpoint blocks, clean up errors in logs

src/chainparams.cpp, src/chainparams.h, src/coins.cpp, src/coins.h, src/consensus/params.h, src/consensus/upgrades.cpp, src/init.cpp, src/main.cpp, src/miner.cpp, src/primitives/transaction.h, src/rpc/zelnode.cpp, src/version.h, src/wallet/wallet.cpp, src/wallet/wallet.h, src/zelnode/activezelnode.cpp, src/zelnode/obfuscation.cpp, src/zelnode/obfuscation.h, src/zelnode/zelnode.cpp, src/zelnode/zelnode.h
- cb3cae5 -> Updated rebuildzelnodedb rpc call 
- 88b5704 -> Added required fields in chainparams for halving, and added ability to get new flux node collateral amounts
- 2fad24c -> Added enforcment checks on collateral amounts, and added new field to zelnodecachedata object
- 14d9d27 -> Added testnet chainparams block heights for halving, updated protocol version, and enfocement of node protocol version once halving starts
- b99668e -> Make sure we only expire nodes during the transition period. Save time do the task over and over once the halving has been completed
- b19d6c7 -> Increase the minimum confirmation window, and maximum confirmation window to send an update confirmation fluxnode transaction. Added helpful rpc call to get node count for migrated vs non-migrated nodes
e2c1828 - …
=> [Halving] Fluxnode halving, bug fixes, p2sh fluxnode, increase confirm reqs

src/rpc/zelnode.cpp
- Added separation of host and port from ip string before assigning the network
=> [Info] Fix network not populating on flux node list when using multiport

src/Makefile.am, src/coins.cpp, src/coins.h, src/gtest/test_mempool.cpp, src/gtest/test_transaction_builder.cpp, src/gtest/test_validation.cpp, src/init.cpp, src/main.cpp, src/main.h, src/rpc/client.cpp, src/rpc/misc.cpp, src/snapshot/snapshotdb.cpp, src/snapshot/snapshotdb.h, src/txdb.cpp, src/txdb.h, src/zcbenchmarks.cpp
This code adds a new database in a new folder /snapshots
New RPC call **printsnapshot \<timestamp\>**
To take a snapshot add the following to the .conf 
snapshot=\<timestamp\>
or run fluxd with the flag 
-snapshot=\<timestamp\>
The snapshot will be taken on the block height of the next block that comes after the given \<timestamp\>
Example: 
snapshot=1649783322 which is (Tue Apr 12 2022 17:08:42 UTC)
Give the following snapshot: 
` {
"nTime": 1649783322,
"height": 1097936,
"balances": {
"t1Hsc324kffbMX2ehmSMHLB2JBxLn8E76EL": 142.57974269,
"t1HscB7BresscYibF5hiAzotugpnEwAgxki": 0.00200000,
"t1HscB7DDYqKHLXWipvZ7pmmxE1VFPXW5b4": 0.00185900,
"t1HscCUEEMpGtdQzXedWwuc614U7wHiG4JQ": 0.00080000,
............
............
}`
The height 1097936 - has the timestamp of 1649783340, which is 18 …
=> Add ability to create snapshots

src/config/bitcoin-config.h
Found small forgotten changes
rename package from zel to flux, changes year and points to fluxd issues instead of zelcash
=> Zel2flux bin 171

src/coincontrol.h, src/rpc/client.cpp, src/rpc/fluxnode.cpp, src/wallet/rpcwallet.cpp, src/wallet/wallet.cpp, src/wallet/wallet.h
Fixes #94 
Added ability to use the **sendfrom** rpc call and pass in a fromaddress - Flux will only be sent from the fromaddress, and all change will be sent back to this address also - This call was marked as deprecated as it used to use accounts. However, I don't see any reason why we shouldn't allow users to specific a fromaddress if they would like. 
Added ability to use the **sendmany** rpc call and pass in a fromaddress - Flux will only be sent from the fromaddress, and all change will be sent back to this address also.
Added new rpc **consolidateutxos** which will try and take utxo's from a single address, and send them back to the same address in a single utxo
=> [RPC] sendfrom/sendmany , now works with given fromaddress

src/init.cpp
- This was accidently changed during the rename to flux. 
However because this is a change that would break already existing nodes that are using zelnodeindex in the flux.conf we don't want to change it
=> Fix rename on existing configuration flag

CONTRIBUTING.md, src/amount.cpp, src/chainparams.cpp, src/gtest/test_transaction_builder.cpp, src/gtest/test_txid.cpp, src/init.cpp, src/main.cpp, src/protocol.h, src/pubkey.cpp, src/rpc/register.h, src/script/interpreter.h, src/sendalert.cpp, src/test/main_tests.cpp, src/util.cpp, src/wallet/asyncrpcoperation_saplingmigration.cpp, src/wallet/gtest/test_wallet.cpp, src/wallet/wallet.h, src/zelcash/NoteEncryption.hpp, src/zelcash/prf.h, src/zelnode/activezelnode.h
Updated references to "Zel"/"Zelcash"/"Zelnode" to "Flux"/"Fluxnode". This has been done in comments only. Some old/broken URLs also updated.
ReadMe file not updated in this PR but can be done in a separate PR if required.
=> Updated Zel/Zelcash to Flux in comments only. Some old URLs also updated.

src/main.cpp
Should ban nodes that send poorly formatted transactions. 
Fixes: 
EXCEPTION: NSt8ios_base7failureB5cxx11E
Unknown transaction format: iostream error
Zelcash in ProcessMessages()
=> Add ban for unprocessable transactions

src/univalue/include/univalue.h
Between fluxd version 6.0 and 6.1 the output of getblockchaininfo changed from showing a 
pruned: false,
to 
pruned: 0. 
Blockbook doesn't like the integer value so this code allows for booleans to be supported with the pushKV pairing we use for rpc outputs.
=> Support for bool

src/main.cpp, src/main.h, src/rpc/mining.cpp
- Add backwards capabilities for pools using gbt with older "zelnode" vernacular
- Fix type for max reorg method so comparisons are made correctly.
=> Bugfixes for v6.1.0

src/Makefile.am, src/init.cpp, src/main.cpp, src/rpc/cache.cpp, src/rpc/cache.h, src/rpc/fluxnode.cpp, src/zelnode/activezelnode.cpp, src/zelnode/zelnode.cpp, src/zelnode/zelnode.h, src/zelnode/zelnodeconfig.cpp, src/zelnode/zelnodeconfig.h
- For users that are managing lots of nodes in the fluxnode.conf, starting them can cause the daemon to lock up and become unresponsive. 
- For people calling listfluxnodes all the time, there is now a cache that is retained as long as the block height doesn't change
Fixes for this include: 
- Making sure when we loop through vectors of data we are accessing the items by reference(&) instead of copying them into memory. 
- Caching the list of available fluxnodes in memory after the first time we loop through all wallet transactions. Instead of processing through every wallet transaction for each node we want to start. I believe this is the biggest contributor to the daemon locking up as we was LOCK and UNLOCK the wallet critical section. This change will at least free up a lot of locks …
=> Cache Fluxnode list

src/zelnode/activezelnode.cpp
Fixes #220 
The wallet is locked when 
`vector<std::pair<COutput, CAmount>> possibleCoins = SelectCoinsFluxnode(); calls
`pwalletMain->AvailableCoins(vCoins, true, NULL, false, false, ALL_FLUXNODE);`
So the functions that are using the wallet already lock the need critical sections.
=> Remove lock test

src/coincontrol.h, src/init.cpp, src/wallet/rpcwallet.cpp
Fluxpools have reported that they would like the ability to set a default change address for when the are sending payments to miners. The reason for this feature request is because normal transactions generate a new address to be the change address causing the wallet to grow in size. 
To allow this type of feature fluxd now allows two new parameters to be passed to fluxd when starting the application or they can be placed in the flux.conf.
- **defaultchangeaddressmainnet**= valid_mainnet_address
- **defaultchangeaddresstestnet**= valid_testnet_address
The default change address will be assigned if it was passed to the application in either of the mechanisms above, it is a valid address for the network is belongs to, and it will only work with the following rpc calls
- **sendmany**
- …
=> [Feature] Add ability for users to set a default change address

src/init.cpp, src/main.cpp, src/rpc/blockchain.cpp, src/rpc/client.cpp, src/util.cpp, src/util.h
- Stops halving at current block reward
- Improve getchaintips RPC call
- Now defaults to searching the last 100,000 blocks.
- Now accepts a parameter which would force the entire chain search
=> Stop halving

README.md
Update to use autoconf 2.64 which will not upgrade to the latest autoconf.
There is no guarantee about backwards compatibility with autoconf
This was found when trying to build on a system upgraded from 20.04 to 22.04
=> Fix ubuntu upgrade24
