README.md, depends/packages/librustzcash.mk, depends/packages/rust.mk
- Rust improvement to support both linux and windows
- Adding windows build instructions and simplifying linux instructions
=> Windows build notes

src/script/script.cpp
Fixed curly bracket and reorganised
=> Addressindex bitcore fix

src/test/main_tests.cpp, src/wallet/asyncrpcoperation_saplingmigration.cpp, src/wallet/asyncrpcoperation_saplingmigration.h, src/wallet/wallet.cpp
Fixing CI build on :iphone: while :bath:
=> Zcash to Zelcash directory

src/chainparams.cpp, src/chainparams.h, src/chainparamsbase.cpp, src/consensus/params.h, src/consensus/upgrades.cpp, src/crypto/equihash.cpp, src/crypto/equihash.h, src/pow.cpp, src/version.h
- ZelHash implemented
- Public Testnet compatible
- Protocol version 170012
Co-Authored-By: lolliedieb @Lolliedieb
=> ZelHash Implementation

src/miner.cpp, src/miner.h, src/rpc/mining.cpp, src/zelnode/payments.cpp, src/zelnode/payments.h, src/zelnode/zelnodesync.cpp
- Update `getblocktemplate` rpc to get zelnode payouts easier
=> [RPC] Update zelnode for Kamiooka

zcutil/build.sh
added -fPIC to CXXFLAGS and $LIBS_ARG to the ./configure arg.
=> Update build.sh to fix 16.04 compiling issue

src/rpc/zelnode.cpp
- Added new rpc call **getdoslist**
- Added new rpc call **getstartlist**
=> Add ability to get the start and dos zelnode lists via rpc calls

src/net.cpp, src/primitives/transaction.h
fix macos building
better readability for null condition
=> fix macos building

src/init.cpp, src/main.cpp, src/main.h
Adjust limitfreerelay to 500
Adjust max reorg to 30
=> Higher default limitfreerelay

src/rpc/rawtransaction.cpp
- add txhash, outidx, payment_address and full collateral
=> extend TxToJSON for zelnode txs

.travis.yml, zcutil/fetch-params.bat
Setup releases by Travis and testing on Linux, Arm and Windows. 
macOS is disabled as of cost.
Adds fetch of parameters script for windows
note: squash the commits when merging
=> Travis setup

src/bitcoind.cpp, src/chainparams.cpp, src/chainparams.h, src/coins.cpp, src/consensus/params.h, src/init.cpp, src/main.cpp, src/main.h, src/miner.cpp, src/pow.cpp, src/rpc/mining.cpp, src/rpc/zelnode.cpp, src/util.cpp, src/util.h, src/wallet/wallet.cpp, src/zelnode/activezelnode.cpp, src/zelnode/obfuscation.cpp, src/zelnode/obfuscation.h, src/zelnode/payments.cpp, src/zelnode/payments.h, src/zelnode/zelnode.cpp, src/zelnode/zelnode.h, src/zelnode/zelnodeman.cpp, src/zelnode/zelnodeman.h
Important - Before merging, we must update all the TODO with the correct address and values that are needed for a valid fork
Changes:
- Disabled T Address -> Z Address
- If you are moving Z Address amounts, you must spend them all to T Address (vectors must be empty) - We can look into this, and make some changes if this isn't what we want
- Removed the requirements to shield coinbase 
- Added Exchange fund requirements into the coinbase at a certain height
- Added swap pool fund requirements into the coinbase at a certain height and interval
- Added required swap pool and exchange fund to `getblocktemplate` rpc call, so pool can build valid coinbase transactions
- Double the amount of rewards going to flux nodes
- Need to rename files
- Need to rename zelnode types in codebase
Basic = …
=> [WIP] Remove T->Z, Add Exchange Fund, Add Swap Pool Fund

src/init.cpp, src/zelnode/benchmarks.cpp, src/zelnode/benchmarks.h
- added ability to detect zelbenchd/fluxbenchd
- added self path detection ( daemon will always look for zelbenchd/fluxbend on dir where is daemon )
=> Ability to run from any dir fix

src/init.cpp, src/zelnode/benchmarks.cpp
Allow fluxnode to be only on Linux and so fix compilation on other platforms
=> fluxnode Linux specific 

src/config/bitcoin-config.h, src/metrics.cpp, src/util.cpp, src/util.h
=> [INFO] Add version to metrics screen, update copywrite year

depends/patches/boost/darwin.diff, src/crypto/equihash.h
I will no longer need to build in a docker
=> allow building on Ubuntu21.10

src/rpc/zelnode.cpp
Sorry for the delay in this pull request.
I have retested and the filter does return the correct ranks
close #175
=> fix bug in issue 175 - testing required

src/init.cpp, src/util.cpp
Fixed last open question in PR177
=> Revert some zel changes we are not ready for

depends/patches/boost/darwin.diff
=> Patch boost thread_data for ubuntu 21.10 build

src/consensus/validation.h, src/main.cpp, src/miner.cpp
When **getblocktemplate** is called it takes in transactions from the mempool to build a block. If one of those transactions ends up being invalid the **getblocktemplate** rpc call will fail. This can cause pools to stop producing valid block data for their miners to solve. 
This code change makes it so that if **getblocktemplate** fails to produce a valid block because of transactions in the block. The invalid transactions will be removed from the mempool so that the next time **getblocktemplate** is called it won't fail over and over
=> [Pools] Ability for mempool to remove transactions that fail block validity

src/zelnode/zelnode.cpp
- Pools are still running into an issue where they crash because of an map:at error. This has been caused by a known bug in the code revolving around a corner case where a reorganization happens on the same block that a node is confirmed in. Over the year we have fixed this bug in multiple places but it seems that is still occurs every so often. 
- This commit adds a lot of logging in the exact area where the map:at error is occurring. This will hopefully allow us more insight into the data that is causing the crashes so we can fix it. 
Flux Pools
=> Add debug logging for known map:at crash

depends/patches/boost/darwin.diff, src/crypto/equihash.h
This reverts commit 1ad6962f1835aeb81f0e42dc04772825837329b5.
Builds ok on ubuntu 22.04
=> [WIP] Test Mac Build

src/util.cpp
Read and use zelnode.conf file if exists
=> read zelnode.conf file first
